### ISSUE TITLE
Feature | Add custom headers

### ISSUE THREAD

**Issue by zmontgo** [EstebanBorai/mailjet-rs#56]
It would be really helpful to be able to define out own headers to a message we send. For example, a use case I've found particularly pertinent when working with the JavaScrpt API wrapper is this: `Headers: { "Reply-To": "nobody@example.com" }`. May be an easy feature addition.

**Comment by EstebanBorai** [comment]
Hi @zmontgo, thanks so much for your interest in this crate!

Yeah, I find it very useful, feel free to provide support for custom headers in a PR.
Please let me know if you don't have enough time to work on this so I can work on it in the next days.

**Comment by zmontgo** [comment]
Certainly! I think I'll try and create a pull request later today. Let's implement that then move forward with the 3.1 support. As I mentioned in the other thread, I'm relatively new to Rust so feel free to take a look and tell me if there are any issues with it!

**Comment by EstebanBorai** [comment]
@zmontgo thanks so much for your initiative! Of course, count on me for any feedback I can provide.

**Comment by EstebanBorai** [comment]
Awesome work on #57 @zmontgo! Im closing this issue as it is now solved in your PR.
